### ISSUE TITLE
Installing Extension Requires Reload

### ISSUE THREAD

**Issue by MrLarjBrain** [Team2901/OnshapeInsertTool#10]
When you install it and open it for the first time it gets stuck on initializing, and then you have to close it and reopen it

**Comment by WilliamBagel** [comment]
It seems like this is because the preferences file needs to be created, but the app doesn't run after the preferences file is created.

**Comment by toebes** [comment]
This doesn't look related to #16 which I was tackling.

**Comment by WilliamBagel** [comment]
This should work now, but you can make sure on your computer before I resolve this issue.

**Comment by toebes** [comment]
I erased my preferences file and revoked application privileges and it appears to work for me
