### ISSUE TITLE
When you have no libraries and click on the My Libraries icon it should show My Libraries in the breadcrumbs

### ISSUE THREAD

**Issue by toebes** [Team2901/OnshapeInsertTool#2]
For example, if I start with a clean install and then go to the Home, I see: ![image](https://github.com/Team2901/OnshapeInsertTool/assets/12609253/b4782633-1918-4049-a41e-fe49fd0a8133)
When I click on the My Libraries icon, it give a blank window (as expected) with the Home breadcrumb, but there is no breadcrumb for the My Libraries.
![image](https://github.com/Team2901/OnshapeInsertTool/assets/12609253/c47fde87-22ef-45b3-aa66-66dcbd2ce3aa)

**Comment by WilliamBagel** [comment]
Resolved in [Preferences change & patch](https://github.com/toebes/onshape_oauthexample/commit/6024a630d5c04f4ef37ef72686df5d625c4d8662)
