### ISSUE TITLE
Empty Folders

### ISSUE THREAD

**Issue by DrewGardner09** [Team2901/OnshapeInsertTool#26]
When I enter folders that I have nothing inside of(Trash, Shared With me, etc), a blank white screen appears. I think it would improve the usability of the extension if it gave a little message that said something like, "No Documents or Folders have been shared with you." 
<img width="773" alt="Screenshot 2023-11-11 103449" src="https://github.com/Team2901/OnshapeInsertTool/assets/144389494/b35ea564-5b82-4871-8b55-b9deeeb8e5b9">
<img width="851" alt="Screenshot 2023-11-11 103516" src="https://github.com/Team2901/OnshapeInsertTool/assets/144389494/544175e1-9bc7-48d9-9dbc-d59f56dac5be">

**Comment by WilliamBagel** [comment]
Fixed 1.0.3
