### ISSUE TITLE
Spam Clicking Bug

### ISSUE THREAD

**Issue by DrewGardner09** [Team2901/OnshapeInsertTool#27]
Whenever you enter a folder and click on it multiple times, instead of just reopening it, it opens the files in the folder however many times you click.

<img width="353" alt="Screenshot 2023-11-28 155634" src="https://github.com/Team2901/OnshapeInsertTool/assets/144389494/6e0d617e-12c2-400b-b7b6-67c3b5bce401">

**Comment by WilliamBagel** [comment]
Fixed in 1e8170b4373c8e15a813ae1b1a74ea81d727bfd3
