### ISSUE TITLE
Page Combining Bug

### ISSUE THREAD

**Issue by DrewGardner09** [Team2901/OnshapeInsertTool#28]
When one folder is loading and you enter another folder, the first folder contents will appear with the second folder co
<img width="340" alt="Screenshot 2023-11-28 160541" src="https://github.com/Team2901/OnshapeInsertTool/assets/144389494/6e66a60a-b901-4661-91b1-9e1f6ed0cd72">
ntents.

**Comment by WilliamBagel** [comment]
Fixed in 1e8170b4373c8e15a813ae1b1a74ea81d727bfd3
