### ISSUE TITLE
Action Menu Library Names

### ISSUE THREAD

**Issue by DrewGardner09** [Team2901/OnshapeInsertTool#33]
In the action menu, when trying to add a document to a library, the Unicode symbols appear with the library names in the dropdown menu.

<img width="334" alt="Screenshot 2024-01-11 173343" src="https://github.com/Team2901/OnshapeInsertTool/assets/144389494/76ed85df-1359-43eb-857c-368f3086bb83">

**Comment by WilliamBagel** [comment]
Fixed in 414638dd8785ebaf47f42ccd4bd64e60b607b919
