### ISSUE TITLE
Inserting a bearing offers more than just the bearing because the DO NOT USE PARTS is named 'PARTS DO NOT USE'

### ISSUE THREAD

**Issue by toebes** [Team2901/OnshapeInsertTool#9]
(This should be a 1 line fix...)

If you attempt to insert the vgroove bearings from goBILDA > MOTION > Bearings > Specialty Bearings > V-Groove Ball Bearings
![image](https://github.com/Team2901/OnshapeInsertTool/assets/12609253/48a6e1b3-82be-411f-ab69-7d952c6d11ac)
It should just insert the bearing, but clicking on the first one https://cad.onshape.com/documents/9376d78e0e5488ef406ae789/w/93c5127fe5c4d6048341d3b4/e/4a4b8805aa32b34621b57335 gives you:
![image](https://github.com/Team2901/OnshapeInsertTool/assets/12609253/b3f2ab62-0588-4a5b-96e1-5cf94cc6ab4b)
Clicking on the second one gives you
https://cad.onshape.com/documents/4f38146bc0abd0dbffa37cef/w/fa9064dc1dd6b37fbdfd1da8/e/5a7bddf1681952a8266aede6
![image](https://github.com/Team2901/OnshapeInsertTool/assets/12609253/dcadf98b-c107-4cac-a8dc-82a8c6600634)

Looking at both models, they seem to follow the standard of having the parts with a "Do not use these parts" and the tab and the information for it appears to be correct.  

![image](https://github.com/Team2901/OnshapeInsertTool/assets/12609253/adb1329e-3daf-4761-9334-d5b5470ac4d6)

[getInsertChoices](https://github.com/Team2901/OnshapeInsertTool/blob/main/app/app.ts#L1731-L1880) should filter them out, but the check on line [1838](https://github.com/Team2901/OnshapeInsertTool/blob/029a5a8dfb86420efffb72d768eaa0bd7852c932/app/app.ts#L1838C28-L1838C28) Looks for the string 'DO NOT USE THESE PARTS' but the string in the model is 'PARTS DO NOT USE' so we should update the app to look for that string too.

**Comment by WilliamBagel** [comment]
This should be resolved now, @toebes you can make sure.
